### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by lawrence-lee**
I made a few minor changes and one major change.
The major change being moving the installation instructions to lower on the page. My thought process was to help users get to the "How do I use this" portion of the guide faster. 

Another thing to note is, I'm not sure if the cleanup `liferay` is the same as `How to Uninstall`. If not, can we add a `How to Uninstall` section?

### CODE REVIEW

**Review by rotty3000 — CHANGES_REQUESTED** [review]
Can we keep everything un)installation related together? I don't like how this breaks things apart. Think about porting this document by section into official docs where there is a central installation guide.

**Comment by gamerson** [comment]
hey ray, what if we have separate docs in a docs folder
`docs/install.md`
`docs/build.md`
`docs/guide.md` (this is the user guide that lawrence would like to see above the fold)

Then the main readme just have  3 links...
`guide` -> ... 
`install` -> ...
`build` -> ..
what do you think?

**Comment by rotty3000** [comment]
Yeah that would be fine and it's what I've kind of been doing. I just think that until we have a docs site install is the number one issue.

**Comment by gamerson** [comment]
Hey Lawrence, since this is now in "paused" mode, lets revisit this once we pick the effort back up (and we can create tickets in JIRA).  Thanks.

**Pull request closed without merging**
